services:
  mongodb:
    image: mongo:7.0
    container_name: fridgewiseai-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: fridgewiseai
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - fridgewiseai-network

  recognize-anything-api:
    image: mnahkies/recognize-anything-api:latest
    container_name: fridgewiseai-recognize-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MODEL_NAME: ram_plus  # Modello migliore per food recognition
      IMAGE_SIZE: 384
      THRESHOLD: 0.68
    # Rimuovi --gpus all se non hai GPU NVIDIA
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    networks:
      - fridgewiseai-network

volumes:
  mongodb_data:

networks:
  fridgewiseai-network:
    driver: bridge
