services:
  mongodb:
    image: mongo:7.0
    container_name: fridgewiseai-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: fridgewiseai
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - fridgewiseai-network

  recognize-anything-api:
    image: mnahkies/recognize-anything-api:latest
    container_name: fridgewiseai-recognize-api
    restart: unless-stopped
    ports:
      - "8000:8000"
    environment:
      MODEL_NAME: ram_plus  # Modello migliore per food recognition
      IMAGE_SIZE: 384
      THRESHOLD: 0.68
    # Rimuovi --gpus all se non hai GPU NVIDIA
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]
    networks:
      - fridgewiseai-network

  libretranslate:
    image: libretranslate/libretranslate:latest
    container_name: fridgewiseai-libretranslate
    restart: unless-stopped
    ports:
      - "5000:5000"
    environment:
      LT_LOAD_ONLY: en,it,fr,de  # Carica solo le lingue necessarie per performance migliori
      LT_SUGGESTIONS: false      # Disabilita suggerimenti per privacy
      LT_DISABLE_WEB_UI: false   # Mantieni web UI per testing
      LT_UPDATE_MODELS: true     # Aggiorna modelli automaticamente
    volumes:
      - libretranslate_data:/app/db  # Persist dei modelli scaricati
    networks:
      - fridgewiseai-network

volumes:
  mongodb_data:
  libretranslate_data:

networks:
  fridgewiseai-network:
    driver: bridge
