version: '3.8'

services:
  mongodb:
    image: mongo:7.0
    container_name: fridgewiseai-mongo
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_DATABASE: fridgewiseai
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - fridgewiseai-network

volumes:
  mongodb_data:

networks:
  fridgewiseai-network:
    driver: bridge
